const CONFIGURATION_ROUTE = "/"
const OFFERS_ROUTE = "/offers"
const CUSTOMERS_ROUTE = "/customers"
const MANAGEMENT_ROUTE = "/management"

export { CONFIGURATION_ROUTE, OFFERS_ROUTE, CUSTOMERS_ROUTE, MANAGEMENT_ROUTE }
